"use client";

import { useState } from "react";
import type { Presentation } from "@/lib/types";
import { getStyleById } from "@/lib/presets";

function CoverSlide({ slide, colors }: { slide: { title: string; body: string[] }; colors: Record<string, string> }) {
  return (
    <div className="w-full h-full flex flex-col" style={{ background: `#${colors.white}` }}>
      <div className="flex-[52] flex items-end p-6 relative" style={{ background: `#${colors.dark}` }}>
        <h2 className="text-xl md:text-2xl font-bold leading-tight" style={{ color: `#${colors.white}` }}>{slide.title}</h2>
        <div className="absolute bottom-0 left-0 right-0 h-1" style={{ background: `#${colors.accent}` }} />
      </div>
      <div className="flex-[48] p-4 relative">
        {slide.body?.length > 0 && (
          <p className="text-xs" style={{ color: `#${colors.muted}` }}>{slide.body.join("  ·  ")}</p>
        )}
        <div className="mt-3 w-12 h-0.5" style={{ background: `#${colors.accent}` }} />
        <span className="block mt-2 text-[8px] font-mono italic" style={{ color: `#${colors.line}` }}>Generated by CoSlide</span>
      </div>
    </div>
  );
}

function ContentSlide({ slide, idx, total, colors }: { slide: { title: string; body: string[] }; idx: number; total: number; colors: Record<string, string> }) {
  return (
    <div className="w-full h-full relative" style={{ background: `#${colors.white}` }}>
      <div className="absolute left-0 top-0 w-2 h-full" style={{ background: `#${colors.accent}` }} />
      <div className="absolute top-0 right-0 font-mono text-xs font-bold px-3 py-1.5" style={{ background: `#${colors.dark}`, color: `#${colors.white}` }}>
        {String(idx + 1).padStart(2, "0")}
      </div>
      <div className="ml-4 p-4">
        <h3 className="text-base font-bold mb-1" style={{ color: `#${colors.title}` }}>{slide.title}</h3>
        <div className="w-8 h-0.5 mb-3" style={{ background: `#${colors.accent}` }} />
        <ul className="space-y-1.5">
          {slide.body?.map((b, i) => (
            <li key={i} className="flex items-baseline gap-1.5 text-xs leading-relaxed" style={{ color: `#${colors.body}` }}>
              <span className="text-[8px] shrink-0" style={{ color: `#${colors.accent}` }}>&#9632;</span>
              {b}
            </li>
          ))}
        </ul>
      </div>
      <div className="absolute bottom-0 left-2 right-0 px-3 py-1 flex justify-end" style={{ borderTop: `1px solid #${colors.line}` }}>
        <span className="font-mono text-[8px]" style={{ color: `#${colors.muted}` }}>
          {String(idx + 1).padStart(2, "0")} / {String(total).padStart(2, "0")}
        </span>
      </div>
    </div>
  );
}

function EndingSlide({ slide, colors }: { slide: { title: string; body: string[] }; colors: Record<string, string> }) {
  return (
    <div className="w-full h-full flex flex-col items-center justify-center relative" style={{ background: `#${colors.dark}` }}>
      <div className="absolute top-0 left-0 right-0 h-1" style={{ background: `#${colors.accent}` }} />
      <h2 className="text-xl md:text-2xl font-bold mb-3" style={{ color: `#${colors.white}` }}>{slide.title}</h2>
      <div className="w-16 h-0.5 mb-4" style={{ background: `#${colors.accent}` }} />
      <div className="text-center space-y-1">
        {slide.body?.map((b, i) => (
          <p key={i} className="text-xs leading-relaxed" style={{ color: `#${colors.light}` }}>{b}</p>
        ))}
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-1" style={{ background: `#${colors.accent}` }} />
      <span className="absolute bottom-3 text-[8px] font-mono italic" style={{ color: `#${colors.muted}` }}>Generated by CoSlide</span>
    </div>
  );
}

export default function SlidePreview({ presentation, styleId = "storytelling" }: { presentation: Presentation; styleId?: string }) {
  const [current, setCurrent] = useState(0);
  const total = presentation.slides.length;
  const colors = getStyleById(styleId).colors;

  function renderSlide(idx: number) {
    const slide = presentation.slides[idx];
    if (idx === 0) return <CoverSlide slide={slide} colors={colors} />;
    if (idx === total - 1 && total > 1) return <EndingSlide slide={slide} colors={colors} />;
    return <ContentSlide slide={slide} idx={idx} total={total} colors={colors} />;
  }

  return (
    <div className="border-4 border-black bg-[#F4F1EA]">
      <div className="border-b-4 border-dashed border-black px-4 py-2 flex items-center justify-between">
        <span className="font-mono text-[10px] uppercase tracking-[0.3em]">
          SLIDE PREVIEW
        </span>
        <span className="font-mono text-[10px] uppercase tracking-widest">
          {String(current + 1).padStart(2, "0")} / {String(total).padStart(2, "0")}
        </span>
      </div>

      <div className="relative bg-[#1a1a1a] mx-4 my-4 border-2 border-black">
        <div className="aspect-video">
          {renderSlide(current)}
        </div>
      </div>

      <div className="px-4 pb-4 flex items-center gap-3">
        <button
          onClick={() => setCurrent((c) => Math.max(0, c - 1))}
          disabled={current === 0}
          className="
            px-3 py-1.5 font-mono text-xs uppercase tracking-widest
            border-2 border-black bg-white
            hover:bg-black hover:text-white
            disabled:opacity-30 disabled:cursor-not-allowed disabled:hover:bg-white disabled:hover:text-black
            transition-colors cursor-pointer
          "
        >
          &larr; PREV
        </button>

        <div className="flex-1 flex items-center justify-center gap-1.5 flex-wrap">
          {presentation.slides.map((_, i) => (
            <button
              key={i}
              onClick={() => setCurrent(i)}
              className="w-6 h-4 border border-black transition-colors cursor-pointer"
              style={{
                background: i === current ? `#${colors.accent}` : "#fff",
              }}
              title={`Slide ${i + 1}`}
            />
          ))}
        </div>

        <button
          onClick={() => setCurrent((c) => Math.min(total - 1, c + 1))}
          disabled={current === total - 1}
          className="
            px-3 py-1.5 font-mono text-xs uppercase tracking-widest
            border-2 border-black bg-white
            hover:bg-black hover:text-white
            disabled:opacity-30 disabled:cursor-not-allowed disabled:hover:bg-white disabled:hover:text-black
            transition-colors cursor-pointer
          "
        >
          NEXT &rarr;
        </button>
      </div>
    </div>
  );
}
