import PptxGenJS from "pptxgenjs";
import type { Presentation, LogoConfig } from "./types";
import { getStyleById, type StyleColors } from "./presets";

function addLogo(slide: PptxGenJS.Slide, logo: LogoConfig) {
  const size = 0.7;
  const pos = logo.position === "top-right"
    ? { x: 9.1, y: 0.15 }
    : { x: 0.3, y: 4.7 };
  slide.addImage({ data: logo.data, x: pos.x, y: pos.y, w: size, h: size });
}

function addCoverSlide(pres: PptxGenJS, C: StyleColors, slideData: { title: string; body: string[]; notes?: string }, total: number, logo?: LogoConfig) {
  const slide = pres.addSlide();
  slide.background = { color: C.white };

  slide.addShape(pres.ShapeType.rect, {
    x: 0, y: 0, w: "100%", h: 2.8,
    fill: { color: C.dark },
  });

  slide.addShape(pres.ShapeType.rect, {
    x: 0, y: 2.8, w: "100%", h: 0.06,
    fill: { color: C.accent },
  });

  slide.addText(slideData.title, {
    x: 0.8, y: 0.6, w: 8.4, h: 1.6,
    fontSize: 36, fontFace: "Arial",
    color: C.white, bold: true,
    valign: "bottom",
    lineSpacingMultiple: 1.1,
  });

  if (slideData.body?.length) {
    slide.addText(slideData.body.join("  |  "), {
      x: 0.8, y: 3.2, w: 8.4, h: 0.6,
      fontSize: 14, fontFace: "Arial",
      color: C.muted,
      valign: "top",
    });
  }

  slide.addShape(pres.ShapeType.rect, {
    x: 0.8, y: 4.8, w: 3, h: 0.03,
    fill: { color: C.accent },
  });

  slide.addText("Generated by CoSlide", {
    x: 0.8, y: 5.0, w: 4, h: 0.3,
    fontSize: 8, fontFace: "Courier New",
    color: C.line, italic: true,
  });

  slide.addText(`01 / ${String(total).padStart(2, "0")}`, {
    x: 8.2, y: 5.0, w: 1.5, h: 0.3,
    fontSize: 8, fontFace: "Courier New",
    color: C.line, align: "right",
  });

  if (logo) addLogo(slide, logo);
  if (slideData.notes) slide.addNotes(slideData.notes);
}

function addContentSlide(pres: PptxGenJS, C: StyleColors, slideData: { title: string; body: string[]; notes?: string }, idx: number, total: number, presTitle: string, logo?: LogoConfig) {
  const slide = pres.addSlide();
  slide.background = { color: C.white };

  slide.addShape(pres.ShapeType.rect, {
    x: 0, y: 0, w: 0.2, h: "100%",
    fill: { color: C.accent },
  });

  slide.addShape(pres.ShapeType.rect, {
    x: 8.8, y: 0, w: 1.2, h: 0.45,
    fill: { color: C.dark },
  });
  slide.addText(`${String(idx + 1).padStart(2, "0")}`, {
    x: 8.8, y: 0, w: 1.2, h: 0.45,
    fontSize: 14, fontFace: "Courier New",
    color: C.white, bold: true,
    align: "center", valign: "middle",
  });

  slide.addText(slideData.title, {
    x: 0.6, y: 0.5, w: 8, h: 0.7,
    fontSize: 24, fontFace: "Arial",
    color: C.title, bold: true,
    valign: "top",
  });

  slide.addShape(pres.ShapeType.rect, {
    x: 0.6, y: 1.25, w: 1.6, h: 0.04,
    fill: { color: C.accent },
  });

  if (slideData.body?.length) {
    const bodyObjects: PptxGenJS.TextProps[] = slideData.body.map((text, i) => ({
      text,
      options: {
        fontSize: 15,
        fontFace: "Arial",
        color: C.body,
        bullet: { code: "25A0", color: C.accent },
        breakType: "none" as const,
        paraSpaceBefore: i === 0 ? 0 : 6,
        paraSpaceAfter: 10,
      },
    }));

    slide.addText(bodyObjects, {
      x: 0.6, y: 1.55, w: 8.5, h: 3.2,
      valign: "top",
      lineSpacingMultiple: 1.45,
    });
  }

  slide.addShape(pres.ShapeType.rect, {
    x: 0.6, y: 4.9, w: 8.8, h: 0.015,
    fill: { color: C.line },
  });

  slide.addText(presTitle, {
    x: 0.6, y: 5.0, w: 5, h: 0.3,
    fontSize: 8, fontFace: "Courier New",
    color: C.muted,
  });

  slide.addText(`${String(idx + 1).padStart(2, "0")} / ${String(total).padStart(2, "0")}`, {
    x: 8.0, y: 5.0, w: 1.5, h: 0.3,
    fontSize: 8, fontFace: "Courier New",
    color: C.muted, align: "right",
  });

  if (logo) addLogo(slide, logo);
  if (slideData.notes) slide.addNotes(slideData.notes);
}

function addEndingSlide(pres: PptxGenJS, C: StyleColors, slideData: { title: string; body: string[]; notes?: string }, total: number, logo?: LogoConfig) {
  const slide = pres.addSlide();
  slide.background = { color: C.dark };

  slide.addShape(pres.ShapeType.rect, {
    x: 0, y: 0, w: "100%", h: 0.06,
    fill: { color: C.accent },
  });

  slide.addText(slideData.title, {
    x: 1, y: 1.2, w: 8, h: 1.2,
    fontSize: 36, fontFace: "Arial",
    color: C.white, bold: true,
    align: "center", valign: "middle",
  });

  slide.addShape(pres.ShapeType.rect, {
    x: 3.8, y: 2.5, w: 2.4, h: 0.04,
    fill: { color: C.accent },
  });

  if (slideData.body?.length) {
    const bodyText = slideData.body.join("\n");
    slide.addText(bodyText, {
      x: 1.5, y: 2.9, w: 7, h: 1.8,
      fontSize: 14, fontFace: "Arial",
      color: C.light,
      align: "center", valign: "top",
      lineSpacingMultiple: 1.6,
    });
  }

  slide.addShape(pres.ShapeType.rect, {
    x: 0, y: 5.2, w: "100%", h: 0.06,
    fill: { color: C.accent },
  });

  slide.addText("Generated by CoSlide", {
    x: 3.5, y: 4.9, w: 3, h: 0.3,
    fontSize: 8, fontFace: "Courier New",
    color: C.muted, align: "center", italic: true,
  });

  slide.addText(`${String(total).padStart(2, "0")} / ${String(total).padStart(2, "0")}`, {
    x: 8.2, y: 5.0, w: 1.5, h: 0.3,
    fontSize: 8, fontFace: "Courier New",
    color: C.muted, align: "right",
  });

  if (logo) addLogo(slide, logo);
  if (slideData.notes) slide.addNotes(slideData.notes);
}

export async function generatePPTX(
  data: Presentation,
  styleId: string = "storytelling",
  onSlideProgress?: (slideIndex: number) => void,
  logoConfig?: LogoConfig,
  colorOverrides?: Partial<StyleColors>,
): Promise<Blob> {
  const preset = getStyleById(styleId, colorOverrides);
  const C = preset.colors;
  const pres = new PptxGenJS();

  pres.layout = "LAYOUT_16x9";
  pres.title = data.title;
  pres.author = "CoSlide Generator";
  pres.company = "CoSlide Systems";

  const total = data.slides.length;

  for (let i = 0; i < total; i++) {
    const slideData = data.slides[i];

    if (i === 0) {
      addCoverSlide(pres, C, slideData, total, logoConfig);
    } else if (i === total - 1 && total > 1) {
      addEndingSlide(pres, C, slideData, total, logoConfig);
    } else {
      addContentSlide(pres, C, slideData, i, total, data.title, logoConfig);
    }

    onSlideProgress?.(i);
    await new Promise((r) => setTimeout(r, 150));
  }

  return (await pres.write({ outputType: "blob" })) as Blob;
}

export function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
