import type { Presentation } from "./types";
import { getStyleById, type StyleColors } from "./presets";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderCoverSlide(slide: { title: string; body: string[] }, idx: number, total: number): string {
  const subtitle = slide.body?.length ? slide.body.map(escapeHtml).join("  &middot;  ") : "";
  return `
    <section class="slide slide-cover" data-index="${idx}">
      <div class="cover-dark">
        <div class="cover-accent-bar"></div>
        <h1>${escapeHtml(slide.title)}</h1>
      </div>
      <div class="cover-light">
        ${subtitle ? `<p class="cover-subtitle">${subtitle}</p>` : ""}
        <div class="cover-deco-line"></div>
        <span class="watermark">Generated by CoSlide</span>
      </div>
      <span class="page-num">01 / ${String(total).padStart(2, "0")}</span>
    </section>`;
}

function renderContentSlide(slide: { title: string; body: string[] }, idx: number, total: number): string {
  const bullets = slide.body?.map((b) => `<li><span class="bullet-marker">&#9632;</span> ${escapeHtml(b)}</li>`).join("\n        ") || "";
  return `
    <section class="slide slide-content" data-index="${idx}">
      <div class="left-bar"></div>
      <div class="page-badge">${String(idx + 1).padStart(2, "0")}</div>
      <div class="content-area">
        <h2>${escapeHtml(slide.title)}</h2>
        <div class="title-underline"></div>
        <ul>${bullets}</ul>
      </div>
      <div class="slide-footer">
        <span class="page-num">${String(idx + 1).padStart(2, "0")} / ${String(total).padStart(2, "0")}</span>
      </div>
    </section>`;
}

function renderEndingSlide(slide: { title: string; body: string[] }, idx: number, total: number): string {
  const bodyLines = slide.body?.map((b) => `<p>${escapeHtml(b)}</p>`).join("\n        ") || "";
  return `
    <section class="slide slide-ending" data-index="${idx}">
      <div class="ending-accent-top"></div>
      <h1>${escapeHtml(slide.title)}</h1>
      <div class="ending-deco-line"></div>
      <div class="ending-body">${bodyLines}</div>
      <div class="ending-accent-bottom"></div>
      <span class="watermark-end">Generated by CoSlide</span>
      <span class="page-num-end">${String(total).padStart(2, "0")} / ${String(total).padStart(2, "0")}</span>
    </section>`;
}

function buildCSS(C: StyleColors): string {
  return `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
    background: #1a1a1a; overflow: hidden; width: 100vw; height: 100vh;
  }
  .slide {
    position: absolute; top: 50%; left: 50%;
    width: 960px; height: 540px;
    transform: translate(-50%, -50%); opacity: 0;
    transition: opacity 0.4s ease; pointer-events: none; overflow: hidden;
  }
  .slide.active { opacity: 1; pointer-events: auto; }
  @media (max-width: 1000px) {
    .slide, .slide.active { transform: translate(-50%, -50%) scale(0.7); }
  }

  .slide-cover { background: #${C.white}; display: flex; flex-direction: column; }
  .cover-dark {
    background: #${C.dark}; flex: 0 0 52%; display: flex; align-items: flex-end;
    padding: 40px; position: relative;
  }
  .cover-accent-bar { position: absolute; bottom: 0; left: 0; right: 0; height: 4px; background: #${C.accent}; }
  .cover-dark h1 { color: #${C.white}; font-size: 36px; font-weight: 700; line-height: 1.2; }
  .cover-light { flex: 1; padding: 24px 40px; position: relative; }
  .cover-subtitle { color: #${C.muted}; font-size: 14px; margin-bottom: 20px; }
  .cover-deco-line { width: 80px; height: 3px; background: #${C.accent}; margin-bottom: 12px; }
  .watermark { font-size: 10px; color: #${C.line}; font-family: "Courier New", monospace; font-style: italic; }
  .slide-cover .page-num {
    position: absolute; bottom: 16px; right: 24px;
    font-size: 10px; color: #${C.line}; font-family: "Courier New", monospace;
  }

  .slide-content { background: #${C.white}; }
  .left-bar { position: absolute; left: 0; top: 0; width: 12px; height: 100%; background: #${C.accent}; }
  .page-badge {
    position: absolute; top: 0; right: 0; width: 60px; height: 36px;
    background: #${C.dark}; color: #${C.white}; font-family: "Courier New", monospace;
    font-size: 16px; font-weight: 700; display: flex; align-items: center; justify-content: center;
  }
  .content-area { padding: 36px 40px; margin-left: 12px; }
  .content-area h2 { font-size: 24px; font-weight: 700; color: #${C.title}; margin-bottom: 8px; }
  .title-underline { width: 60px; height: 3px; background: #${C.accent}; margin-bottom: 24px; }
  .content-area ul { list-style: none; padding: 0; }
  .content-area li {
    font-size: 15px; color: #${C.body}; line-height: 1.8; margin-bottom: 8px;
    display: flex; align-items: baseline; gap: 8px;
  }
  .bullet-marker { color: #${C.accent}; font-size: 10px; flex-shrink: 0; }
  .slide-footer {
    position: absolute; bottom: 0; left: 12px; right: 0;
    border-top: 1px solid #${C.line}; padding: 8px 24px; display: flex; justify-content: flex-end;
  }
  .slide-footer .page-num { font-size: 10px; color: #${C.muted}; font-family: "Courier New", monospace; }

  .slide-ending {
    background: #${C.dark}; display: flex; flex-direction: column;
    align-items: center; justify-content: center; text-align: center;
  }
  .ending-accent-top, .ending-accent-bottom {
    position: absolute; left: 0; right: 0; height: 4px; background: #${C.accent};
  }
  .ending-accent-top { top: 0; }
  .ending-accent-bottom { bottom: 0; }
  .slide-ending h1 { color: #${C.white}; font-size: 36px; font-weight: 700; margin-bottom: 16px; }
  .ending-deco-line { width: 100px; height: 3px; background: #${C.accent}; margin-bottom: 24px; }
  .ending-body p { color: #${C.light}; font-size: 14px; line-height: 1.8; }
  .watermark-end {
    position: absolute; bottom: 24px; left: 50%; transform: translateX(-50%);
    font-size: 10px; color: #${C.muted}; font-family: "Courier New", monospace; font-style: italic;
  }
  .page-num-end {
    position: absolute; bottom: 16px; right: 24px;
    font-size: 10px; color: #${C.muted}; font-family: "Courier New", monospace;
  }

  .nav-bar {
    position: fixed; bottom: 24px; left: 50%; transform: translateX(-50%);
    display: flex; gap: 8px; align-items: center; z-index: 100;
    background: rgba(0,0,0,0.7); padding: 8px 16px; border-radius: 8px;
  }
  .nav-dot {
    width: 10px; height: 10px; border-radius: 50%; background: #555;
    cursor: pointer; transition: background 0.2s;
  }
  .nav-dot.active { background: #${C.accent}; }
  .nav-btn {
    background: none; border: 1px solid #666; color: #ccc;
    padding: 4px 12px; cursor: pointer; font-family: "Courier New", monospace;
    font-size: 12px; transition: all 0.2s;
  }
  .nav-btn:hover { background: #${C.accent}; border-color: #${C.accent}; color: #fff; }`;
}

export function generateHTML(data: Presentation, styleId: string = "storytelling"): string {
  const preset = getStyleById(styleId);
  const C = preset.colors;
  const total = data.slides.length;

  const slidesHtml = data.slides.map((slide, i) => {
    if (i === 0) return renderCoverSlide(slide, i, total);
    if (i === total - 1 && total > 1) return renderEndingSlide(slide, i, total);
    return renderContentSlide(slide, i, total);
  }).join("\n");

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(data.title)}</title>
<style>${buildCSS(C)}</style>
</head>
<body>
${slidesHtml}
<div class="nav-bar">
  <button class="nav-btn" onclick="go(-1)">&larr;</button>
  ${data.slides.map((_, i) => `<div class="nav-dot" data-i="${i}" onclick="goTo(${i})"></div>`).join("")}
  <button class="nav-btn" onclick="go(1)">&rarr;</button>
</div>
<script>
  let cur = 0;
  const slides = document.querySelectorAll('.slide');
  const dots = document.querySelectorAll('.nav-dot');
  function show() {
    slides.forEach((s, i) => s.classList.toggle('active', i === cur));
    dots.forEach((d, i) => d.classList.toggle('active', i === cur));
  }
  function go(d) { cur = Math.max(0, Math.min(slides.length - 1, cur + d)); show(); }
  function goTo(i) { cur = i; show(); }
  show();
  document.addEventListener('keydown', e => {
    if (e.key === 'ArrowRight' || e.key === ' ') go(1);
    if (e.key === 'ArrowLeft') go(-1);
  });
</script>
</body>
</html>`;
}

export function downloadHTML(data: Presentation, styleId: string = "storytelling") {
  const html = generateHTML(data, styleId);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const sanitized = data.title.replace(/[^a-zA-Z0-9\u4e00-\u9fff\s\-_]/g, "").trim() || "presentation";
  a.download = `${sanitized}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
